### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hatemfadi** [ibm-watson-iot/iot-starter-for-android#10]
When trying to connect the android application, i am getting the following error and the app is crashing. Yesterday everything was working fine and i was able to connect and publish my data to the iot starter application, but today i am getting this error. 

`11-14 15:46:59.356 5265-6433/com.ibm.iot.android.iotstarter E/AndroidRuntime: FATAL EXCEPTION: MQTT Con: d:****:*******:*****
                                                                              Process: com.ibm.iot.android.iotstarter, PID: 5265
                                                                              java.lang.NullPointerException: cancel() called with a null PendingIntent
                                                                                  at android.app.AlarmManager.cancel(AlarmManager.java:901)
                                                                                  at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:86)
                                                                                  at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:369)
                                                                                  at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:694)
                                                                                  at java.lang.Thread.run(Thread.java:764)`

Any help would be appreciated, thank you.

**Comment by robert17** [comment]
This looks like the same issue which is being reported here: https://github.com/eclipse/paho.mqtt.android/issues/260

The actual cause for your connection issues is likely due to a change in the public messaging certificate of the IoT service. The certificate was updated since it would be expiring soon, and this application happened to be using the leaf certificate rather than a CA in its truststore.

An updated truststore has been delivered.
