### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by DattatrayHinge** [ibm-watson-iot/iot-starter-for-android#11]
Running this code on android emulator and got certificate error. 
Not sure what is the problem 

11-15 01:11:24.673 3561-3561/com.ibm.iot.android.iotstarter E/com.ibm.iot.android.iotstarter.utils.MyIoTActionListener: .onFailure() entered
11-15 01:11:24.676 3561-3561/com.ibm.iot.android.iotstarter E/com.ibm.iot.android.iotstarter.utils.MyIoTActionListener: .handleConnectFailure() entered
11-15 01:11:24.682 3561-3561/com.ibm.iot.android.iotstarter E/com.ibm.iot.android.iotstarter.utils.MyIoTActionListener: .handleConnectFailure() - Failed with exception
                                                                                                                        MqttException (0) - javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
                                                                                                                            at java.lang.Thread.run(Thread.java:764)
                                                                                                                         Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                                            at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(:com.google.android.gms@11577470:27)
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:97)
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
                                                                                                                            at java.lang.Thread.run(Thread.java:764) 
                                                                                                                         Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
                                                                                                                            at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                                                                            at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
                                                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                                                            at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@11577470:2)
                                                                                                                            at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@11577470:6)
                                                                                                                            at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(:com.google.android.gms@11577470:6)
                                                                                                                            at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                                                                            at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(:com.google.android.gms@11577470:24)
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:97) 
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676) 
                                                                                                                            at java.lang.Thread.run(Thread.java:764) 
                                                                                                                         Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646) 
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605) 
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495) 
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418) 
                                                                                                                            at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339) 
                                                                                                                            at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94) 
                                                                                                                            at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88) 
                                                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                                            at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@11577470:2) 
                                                                                                                            at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@11577470:6) 
                                                                                                                            at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(:com.google.android.gms@11577470:6) 
                                                                                                                            at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                                                                                            at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(:com.google.android.gms@11577470:24) 
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:97) 
                                                                                                                            at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676) 
                                                                                                                            at java.lang.Thread.run(Thread.java:764)

**Comment by DattatrayHinge** [comment]
So what is the solution now
